-- Database-backed feature flags. The backend is the source of truth for whether a
-- feature is available; the frontend only mirrors these values to hide UI. Each row is
-- one flag scoped to one environment, so the same feature_key can differ per environment.
CREATE TABLE feature_flags (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_key        VARCHAR(150) NOT NULL,
    display_name       VARCHAR(200) NOT NULL,
    description        VARCHAR(500),
    environment        VARCHAR(50)  NOT NULL,
    enabled            BOOLEAN      NOT NULL DEFAULT FALSE,
    flag_type          VARCHAR(50)  NOT NULL DEFAULT 'RELEASE',
    rollout_percentage INTEGER      NOT NULL DEFAULT 100,
    configuration      JSONB,
    owner              VARCHAR(150),
    expires_at         TIMESTAMP,
    removal_condition  VARCHAR(500),
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_feature_flags_key_environment
        UNIQUE (feature_key, environment),

    CONSTRAINT chk_feature_flags_rollout
        CHECK (rollout_percentage BETWEEN 0 AND 100)
);

-- feature_key + environment is the primary runtime lookup; the unique constraint already
-- backs it, but these single-column indexes serve admin/reporting scans (expired flags,
-- all rows for one environment, enabled-only listings).
CREATE INDEX idx_feature_flags_feature_key ON feature_flags (feature_key);
CREATE INDEX idx_feature_flags_environment ON feature_flags (environment);
CREATE INDEX idx_feature_flags_enabled ON feature_flags (enabled);
CREATE INDEX idx_feature_flags_expires_at ON feature_flags (expires_at);
